PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

PREFIX qptdat: <http://plasma-mds.org/qptdat#>
SELECT *
WHERE { 
	?source qptdat:isSourceOf ?experiment .
	?source rdf:type qptdat:PlasmaJet .
	?source qptdat:specifiedBy ?specification . 
	?specification qptdat:frequencyValue ?frequency .
}
